version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: America/New_York
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "10:15"
      timezone: America/New_York
    open-pull-requests-limit: 5
    groups:
      test-dependencies:
        dependency-type: development
        patterns:
          - "*"
