#pragma once

// Versioned wire constants shared with Tappy.Windows.ExclusiveInput. The
// stage-one driver does not expose these IOCTLs yet; freezing the layout now
// prevents the broker and future raw-PDO implementation from drifting.

#define TAPPY_FILTER_PROTOCOL_VERSION 1UL
#define TAPPY_FILTER_MAXIMUM_EVENTS_PER_READ 256UL
#define TAPPY_FILTER_MINIMUM_WATCHDOG_MS 250UL
#define TAPPY_FILTER_MAXIMUM_WATCHDOG_MS 2000UL

#define TAPPY_FILTER_DEVICE_TYPE 0x8000UL

#define IOCTL_TAPPY_FILTER_QUERY_STATUS \
    CTL_CODE(TAPPY_FILTER_DEVICE_TYPE, 0x800, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_TAPPY_FILTER_BEGIN_AUTHENTICATED_SESSION \
    CTL_CODE(TAPPY_FILTER_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_TAPPY_FILTER_SET_INSTANCE_POLICY \
    CTL_CODE(TAPPY_FILTER_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_TAPPY_FILTER_HEARTBEAT \
    CTL_CODE(TAPPY_FILTER_DEVICE_TYPE, 0x803, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_TAPPY_FILTER_READ_EVENTS \
    CTL_CODE(TAPPY_FILTER_DEVICE_TYPE, 0x804, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_TAPPY_FILTER_FORCE_FAIL_OPEN \
    CTL_CODE(TAPPY_FILTER_DEVICE_TYPE, 0x805, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

C_ASSERT(IOCTL_TAPPY_FILTER_QUERY_STATUS == 0x8000E000UL);
C_ASSERT(IOCTL_TAPPY_FILTER_BEGIN_AUTHENTICATED_SESSION == 0x8000E004UL);
C_ASSERT(IOCTL_TAPPY_FILTER_SET_INSTANCE_POLICY == 0x8000E008UL);
C_ASSERT(IOCTL_TAPPY_FILTER_HEARTBEAT == 0x8000E00CUL);
C_ASSERT(IOCTL_TAPPY_FILTER_READ_EVENTS == 0x8000E010UL);
C_ASSERT(IOCTL_TAPPY_FILTER_FORCE_FAIL_OPEN == 0x8000E014UL);

typedef enum _TAPPY_FILTER_MODE
{
    TappyFilterModePassThrough = 0,
    TappyFilterModeCaptureAndSuppress = 1
} TAPPY_FILTER_MODE;

typedef enum _TAPPY_FILTER_ROLE
{
    TappyFilterRoleUnassigned = 0,
    TappyFilterRoleProtectedPrimary = 1,
    TappyFilterRoleConfigurableSecondary = 2
} TAPPY_FILTER_ROLE;

#define TAPPY_FILTER_EVENT_BREAK 0x0001U
#define TAPPY_FILTER_EVENT_E0 0x0002U
#define TAPPY_FILTER_EVENT_E1 0x0004U

// {49A38E1B-8B15-4EAB-BF6D-57D56D098ECC}
DEFINE_GUID(
    GUID_DEVCLASS_TAPPY_KEYBOARD_FILTER,
    0x49a38e1b, 0x8b15, 0x4eab, 0xbf, 0x6d, 0x57, 0xd5, 0x6d, 0x09, 0x8e, 0xcc);

// {29381853-4B50-4A46-9AF6-7A44BFD8336B}
DEFINE_GUID(
    GUID_DEVINTERFACE_TAPPY_KEYBOARD_FILTER,
    0x29381853, 0x4b50, 0x4a46, 0x9a, 0xf6, 0x7a, 0x44, 0xbf, 0xd8, 0x33, 0x6b);

typedef struct _TAPPY_FILTER_SESSION_REQUEST_V1
{
    ULONG ProtocolVersion;
    ULONG Size;
    ULONGLONG TokenLow;
    ULONGLONG TokenHigh;
} TAPPY_FILTER_SESSION_REQUEST_V1, *PTAPPY_FILTER_SESSION_REQUEST_V1;

typedef struct _TAPPY_FILTER_POLICY_REQUEST_V1
{
    ULONG ProtocolVersion;
    ULONG Size;
    ULONGLONG TokenLow;
    ULONGLONG TokenHigh;
    ULONGLONG PolicyGeneration;
    ULONG Role;
    ULONG RequestedMode;
    ULONG WatchdogTimeoutMilliseconds;
    ULONG Reserved;
} TAPPY_FILTER_POLICY_REQUEST_V1, *PTAPPY_FILTER_POLICY_REQUEST_V1;

typedef struct _TAPPY_FILTER_HEARTBEAT_REQUEST_V1
{
    ULONG ProtocolVersion;
    ULONG Size;
    ULONGLONG TokenLow;
    ULONGLONG TokenHigh;
    ULONGLONG PolicyGeneration;
} TAPPY_FILTER_HEARTBEAT_REQUEST_V1, *PTAPPY_FILTER_HEARTBEAT_REQUEST_V1;

typedef struct _TAPPY_FILTER_READ_REQUEST_V1
{
    ULONG ProtocolVersion;
    ULONG Size;
    ULONGLONG TokenLow;
    ULONGLONG TokenHigh;
    ULONG MaximumEvents;
    ULONG Reserved;
} TAPPY_FILTER_READ_REQUEST_V1, *PTAPPY_FILTER_READ_REQUEST_V1;

typedef struct _TAPPY_FILTER_EVENT_V1
{
    ULONGLONG Sequence;
    ULONGLONG PolicyGeneration;
    USHORT MakeCode;
    USHORT Flags;
    USHORT UnitId;
    USHORT Reserved;
} TAPPY_FILTER_EVENT_V1, *PTAPPY_FILTER_EVENT_V1;

typedef struct _TAPPY_FILTER_STATUS_V1
{
    ULONG ProtocolVersion;
    ULONG EffectiveMode;
    ULONG Role;
    ULONG WatchdogArmed;
    ULONG WatchdogTimeoutMilliseconds;
    ULONG Reserved;
    ULONGLONG PolicyGeneration;
    ULONGLONG LastSequence;
    ULONGLONG RingOverflowCount;
} TAPPY_FILTER_STATUS_V1, *PTAPPY_FILTER_STATUS_V1;

C_ASSERT(sizeof(TAPPY_FILTER_EVENT_V1) == 24);
C_ASSERT(sizeof(TAPPY_FILTER_STATUS_V1) == 48);
C_ASSERT(sizeof(TAPPY_FILTER_SESSION_REQUEST_V1) == 24);
C_ASSERT(sizeof(TAPPY_FILTER_POLICY_REQUEST_V1) == 48);
C_ASSERT(sizeof(TAPPY_FILTER_HEARTBEAT_REQUEST_V1) == 32);
C_ASSERT(sizeof(TAPPY_FILTER_READ_REQUEST_V1) == 32);
